// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Aug 26 22:30:22 2019

top top_inst
(
	.CLOCK(CLOCK_sig) ,	// input  CLOCK_sig
	.ADC_DOUT(ADC_DOUT_sig) ,	// input  ADC_DOUT_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.rs232_external_connection_rxd(rs232_external_connection_rxd_sig) ,	// input  rs232_external_connection_rxd_sig
	.ADC_SCLK(ADC_SCLK_sig) ,	// output  ADC_SCLK_sig
	.ADC_CS_N(ADC_CS_N_sig) ,	// output  ADC_CS_N_sig
	.ADC_DIN(ADC_DIN_sig) ,	// output  ADC_DIN_sig
	.led_external_connection_export(led_external_connection_export_sig) ,	// output [7:0] led_external_connection_export_sig
	.rs232_external_connection_txd(rs232_external_connection_txd_sig) 	// output  rs232_external_connection_txd_sig
);

